// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAViMYyQ5JfSX_DMmUoqANDmHvK6ox72qY',
    appId: '1:992553463677:web:1cdf6081cbcbc7ddcc2614',
    messagingSenderId: '992553463677',
    projectId: 'stavax-new',
    authDomain: 'stavax-new.firebaseapp.com',
    storageBucket: 'stavax-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvk6obu_cvLFMauUTxLHIApb22Ts1qFwc',
    appId: '1:992553463677:android:a6fe0cadd15422fdcc2614',
    messagingSenderId: '992553463677',
    projectId: 'stavax-new',
    storageBucket: 'stavax-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBwoc8iAvpIJsIuGTEzV9ud03AmPFCC1E',
    appId: '1:992553463677:ios:52c6223bb61acdbbcc2614',
    messagingSenderId: '992553463677',
    projectId: 'stavax-new',
    storageBucket: 'stavax-new.appspot.com',
    iosBundleId: 'com.example.stavaxNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBwoc8iAvpIJsIuGTEzV9ud03AmPFCC1E',
    appId: '1:992553463677:ios:756b25a2e64501e9cc2614',
    messagingSenderId: '992553463677',
    projectId: 'stavax-new',
    storageBucket: 'stavax-new.appspot.com',
    iosBundleId: 'com.example.stavaxNew.RunnerTests',
  );
}
